blog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    text = TextAreaField('Text',validators=[DataRequired()])
    submit = SubmitField('Post')

blog/blog_posts/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from blog import db
from blog.models import BlogPost
from blog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

# create
@blog_posts.route('/create',methods={'GET','POST'})
@login_required
def create_post():
    # create form
    form = BlogPostForm()

    # validate and pass form data
    if form.validate_on_submit():
        blog_post = BlogPost(title=form.title.data,
                            text=form.text.data,
                            user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Created')
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)

# view
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,date=blog_post.date_time,post=blog_post)

# update
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update_post(blog_post_id):
    # get post
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    # validate user
    if blog_post.author != current_user:
        abort(403)
    
    # create form and pass form data
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data

        db.session.commit()
        flash('Blog Post Updated')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))

    # display post already in db in the form
    elif request.method == "GET":
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    
    return render_template('create_post.html',title='Updating Post',form=form)

# delete
@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Has Been Deleted')
    return redirect(url_for('core.index'))

blog/core/views.py
from flask import render_template,request,Blueprint
from blog.models import BlogPost

core =Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date_time.desc()).paginate(page=page,per_page=5)
    return render_template('index.html',blog_posts=blog_posts)

@core.route('/about')
def info():
    return render_template('about.html')

blog/users/views.py
from flask import render_template,url_for,flash,redirect,Blueprint,request
from flask_login import login_user,current_user,logout_user,login_required
from blog import db
from blog.models import User, BlogPost
from blog.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from blog.users.image_handler import add_profile_picture


users = Blueprint('users',__name__)

# register user
@users.route('/registration',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)

# login user
@users.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Log in successful!')

            # validating already logged in users to access login pages that require logging in
            next_page = request.args.get('next')
            if next_page==None or not next_page[0]=='/':
                next_page = url_for('core.index')
            return redirect(next_page)

    return render_template('login.html',form=form)

# loguout user
@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.index'))

# account/update
@users.route('/account',methods=['GET','POST'])
@login_required
def account_update():
    form = UpdateUserForm()

    if form.validate_on_submit():
        if form.profile_picture.data:
            username = current_user.username
            picture = add_profile_picture(form.profile_picture.data,username)
            current_user.profile_image = picture

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated')
        return redirect(url_for('users.account_update'))

    elif request.method=="GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename='profile_images/'+current_user.profile_image)

    return render_template('account.html',profile_image=profile_image,form=form)

# user's blog list
@users.route("/<username>")
def user_posts(username):
    # request a page -> cycle through posts using pages
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date_time.desc()).paginate(page=page,per_page=5)

    return render_template('user_posts.html',blog_posts=blog_posts,user=user)

blog/templates/about.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>About our company</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda recusandae praesentium ratione quam obcaecati quia et tenetur officiis deserunt numquam neque tempore ut exercitationem quidem iure, perferendis pariatur mollitia adipisci?</p>
    </div>
{% endblock content %}

blog/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <div align='center'>
            <h1>{{current_user.username}}, you're welcome</h1>
            <img align='center' src="{{url_for('static',filename='profile_images/'+current_user.profile_image)}}">
        </div>
    </div>

    <div class="container">
        <form method="POST" action="" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.username.label(class='form-group')}}{{form.username(class='form-control')}} <br>
            </div>
            <div class="form-group">
                {{form.email.label(class='form-group')}}{{form.email(class='form-control')}} <br>
            </div>
            <div class="form-group">
                {{form.profile_picture.label(class='form-group')}}{{form.profile_picture(class='form-control')}} <br>
            </div>
            <div class="form-group">
                {{form.submit(class='btn btn-primary')}}
            </div> 
            
        </form>
    </div>
{% endblock content %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/nbase.css')}}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Company Blog</title>
</head>
<body>
    <div class="navbar navbar-dark bg-dark">
        <ul class="nav" style="color: aliceblue;">
            <li class="nav-link">
                <a href="{{url_for('core.index')}}">Home</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('core.info')}}">About</a>
            </li>
    
            {% if current_user.is_authenticated %}
            <li class="nav-link">
                <a href="{{url_for('users.logout')}}">Log Out</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.account_update')}}">Account</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('blog_posts.create_post')}}">Create Post</a>
            </li>
            {% else %}
            <li class="nav-link">
                <a href="{{url_for('users.login')}}">Log In</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.register')}}">Register</a>
            </li>
            {% endif %}
        </ul>
    </div>

    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
</body>
</html>

blog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{title}}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published on: {{date.strftime('%B %d, %Y')}}</h3>
  <p>{{post.text}}</p>
  <div>
    {% if post.author==current_user %}
    <div>
      <a href="{{url_for('blog_posts.update_post',blog_post_id=post.id)}}">Update</a>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
    </div>
</div>

  {% endif %}
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the post?</p>
      </div>
      <div class="modal-footer">
        <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

blog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
    <div class="container">

        <form class = "form-group" method="POST">
            {{form.hidden_tag()}}

        <div class="form-group">
            {{form.title.label(class="form-control-label")}}{{form.title(class="form-control form-control-lg")}} <br>
        </div>
        <div class="form-group">
            {{form.text.label(class="form-control-label")}}{{form.text(class="form-control form-control-lg")}} <br>
        </div>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}} <br>
        </div>
        </form>
        
        
    </div>
{% endblock content %}

blog/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Company Blog</h1>
</div>

<div class="container">
  {% for post in blog_posts.items %}
  <div class="card">
    <div class="card-body">
      <h2><a class="card-title" href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
      Written by: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>
      <p>Published on: {{post.date_time.strftime('%Y-%m-%d')}}</p>
      <a class="btn btn-primary" href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">Read Blog Post</a>
    </div>
  </div>
  {% endfor %}
</div>

<nav aria-label="Page Navigation example">
  <ul class="pagination justify-content-center">
    {% for page_number in blog_posts.iter_pages(left_edge=1,left_current=1,right_current=1,right_edge=2) %}
    {% if blog_posts.page == page_number %}
    <li class='page-item diabled'>
      <a class="page-link" href="{{url_for('core.index',page=page_number)}}">{{page_number}}</a>
    </li>
    {% else %}
    <li class='page-item'>
      <a class="page-link" href="{{url_for('core.index',page=page_number)}}">{{page_number}}</a>
    </li>
    {% endif %}
    {% endfor %}
  </ul>

</nav>
{% endblock content %}

blog/templates/login.html
{% extends "base.html" %}
{% block content %}
    <form class = "jumbotron" method="POST">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.email.label}}{{form.email}} <br>
        </div>
        <div class="form-group">
            {{form.password.label}}{{form.password}} <br>
        </div>
        <div class="form-group">
            {{form.password.label}}{{form.password}} <br>
        </div>
        <div class="form-group">
            {{form.submit(class='btn btn-primary')}}
        </div>
        
    </form>
{% endblock content %}

blog/templates/register.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
        <div class="jumbotron">
            {{form.hidden_tag()}}
        <div class="form-group">
            {{form.email.label}}{{form.email}} <br>
        </div>
        <div class="form-group">
            {{form.username.label}}{{form.username}} <br>
        </div>
        <div class="form-group">
            {{form.password.label}}{{form.password}} <br>
        </div>
        <div class="form-group">
            {{form.password_confirm.label}}{{form.password_confirm}} <br>
        </div>      
        <div class="form-group">
            {{form.submit(class='btn btn-primary')}}
        </div>
        </div>
        
    </form>
{% endblock content %}

blog/templates/user_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1>{{user.username}}, Welcome to BlogPosts</h1>
      <img src="{{url_for('static',filename='profile_images/'+user.profile_image)}}">
    </div>
  </div>

  {% for post in blog_posts.items %}
  <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
  Written By: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>
  <p class="text-muted">Published on: {{post.date_time.strftime("%Y-%m-%d")}}</p>
  <br>
  <p>{{post.text}}</p>
  <br>
  {% endfor %}

</div>

<nav aria-label="Page Navigation example">
  <ul class="pagination justify-content-center">
    {% for page_number in blog_posts.iter_pages(left_edge=1,left_current=1,right_current=1,right_edge=2) %}
    {% if blog_posts.page == page_number %}
    <li class='page-item diabled'>
      <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_number)}}">{{page_number}}</a>
    </li>
    {% else %}
    <li class='page-item'>
      <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_number)}}">{{page_number}}</a>
    </li>
    {% endif %}
    {% endfor %}
  </ul>

</nav>

{% endblock content %}